allin:
  networks:
    host: 127.0.0.1
    port: 45672
    netty:
      bossCount: 1
      workerCount: 5
      keepAlive: false
      backlog: 10


spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin