server:
  port: 8888

spring:
  application:
    name: simulator
  profiles:
    default: local

  datasource:
    url: jdbc:h2:mem:~/langrisser
    #    url: jdbc:h2:tcp://localhost/~/langrisser
    username: sa
    password:
    driver-class-name: org.h2.Driver