
# default
spring:
  profiles:
    active: local
  messages:
    basename: message, errors
    encoding: UTF-8


allin:
  message: property
  hazelcast:
    receivers:
      - name: order
        listener-count: 2
        worker-count: 5
    senders:
      - name: order
        sender-count: 2
      - name: risk
        sender-count: 1


mybatis:
  type-aliases-package: develop.x.betting
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE